services:
    training_user_naming.provider.entity_name_decorator:
        class: 'Training\Bundle\UserNamingBundle\Provider\EntityNameProviderDecorator'
        decorates: 'oro_locale.entity_name_provider'
        decoration_inner_name: 'oro_locale.entity_name_provider.original'
        public: false
        arguments:
            - '@oro_locale.entity_name_provider.original'
            - '@training_user_naming.provider.user_full_name'
        tags:
            - { name: oro_entity.name_provider, priority: -80 }

    training_user_naming.provider.user_full_name:
        class: 'Training\Bundle\UserNamingBundle\Provider\UserFullNameProvider'
        public: false

    training_user_naming.event_listener.user_view_naming:
        class: 'Training\Bundle\UserNamingBundle\EventListener\UserViewNamingListener'
        arguments:
            - '@doctrine'
            - '@oro_security.security_facade'
        tags:
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.userView, method: onUserView }

    training_user_naming.entity_listener.naming_format_modification:
        class: 'Training\Bundle\UserNamingBundle\EventListener\NamingFormatModificationListener'
        arguments:
            - '@oro_message_queue.message_producer'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Training\Bundle\UserNamingBundle\Entity\UserNamingType', event: postPersist }
            - { name: doctrine.orm.entity_listener, entity: 'Training\Bundle\UserNamingBundle\Entity\UserNamingType', event: preUpdate }

    training_user_naming.async.name_example_generation_processor:
        class: 'Training\Bundle\UserNamingBundle\Async\NameExampleGenerationProcessor'
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@training_user_naming.provider.user_full_name'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }
